function [cnn3d_model] = dss_config(feaName,pos_include_gt,rb_dis,box_reg,proposal_dir,fullbox)
%%
training_opts = struct('svm_C',10^-3, ...
                      'bias_mult',10,...
                      'pos_loss_weight',2, ...
                      'layer',5,...
                      'checkpoint',100,...
                      'max_hard_epochs',1,...
                      'retrain_limit',2000,...
                      'evict_thresh', -1.2,...
                      'hard_thresh',-1.0001,...
                      'neg_ovr_thresh',0.1,...% 2D it is 0.3
                      'pos_ovr_thresh',0.3,...
                      'addboxsize',1,...
                      'onlygtbox',0,...
                      'combinefea',0,...
                      'normfea',0,...
                      'pos_include_po',1,...
                      'pos_include_gt',pos_include_gt,...
                      'rb_dis',rb_dis,...
                      'box_reg',box_reg,...
                      'proposal_dir',proposal_dir,...
                      'fullbox',fullbox);
                  

%%
opt = dss_initPath();
conf.feaName = feaName;
conf.SUNrgbd_toolbox = opt.SUNrgbd_toolbox;
conf.dataRoot =opt.data_root;
conf.feat_root = opt.feature_mat_dir;
conf.feat_cachedir = [conf.feat_root  '/' conf.feaName '/'];

if fullbox
   conf.sizemodel_dir = ['./sizedistrubution/sizedata_full/'];
else
   conf.sizemodel_dir = ['./sizedistrubution/sizedata_tight/'];
end

conf.cache_dir =['../cache/' conf.feaName '/']; 
cnn3d_model.conf = conf;
cnn3d_model.training_opts = training_opts;
cnn3d_model.cache_name = conf.feaName;
display(conf.cache_dir);
